import { BankCard } from "@/types";

export const BANK_CARDS: BankCard[] = [
  {
    id: "visa-platinum",
    badge: "Most Popular",
    badgeTone: "popular",
    title: "Credit Card",
    network: "VISA",
    cardName: "Visa Platinum",
    benefits: [
      "5% cashback on all spends",
      "Airport lounge access",
      "2X reward points",
      "Zero forex markup",
    ],
    cta: "Apply Now",
  },
  {
    id: "mastercard-gold",
    badge: "Credit Card",
    badgeTone: "popular",
    title: "Credit Card",
    network: "MC",
    cardName: "MasterCard Gold",
    benefits: [
      "10% cashback on dining",
      "Global acceptance",
      "Contactless payments",
      "EMI on purchases",
    ],
    cta: "Apply Now",
  },
  {
    id: "rupay-classic",
    badge: "Free",
    badgeTone: "free",
    title: "Debit Card",
    network: "RUPAY",
    cardName: "RuPay Classic",
    benefits: [
      "Free UPI transactions",
      "Insurance coverage",
      "Domestic acceptance",
      "Zero annual fee",
    ],
    cta: "Apply Now",
  },
  {
    id: "corporate-card",
    badge: "Enterprise",
    badgeTone: "enterprise",
    title: "Corporate Card",
    network: "VISA",
    cardName: "Business Card",
    benefits: [
      "GST invoice generation",
      "Expense management",
      "Employee sub-cards",
      "Higher credit limit",
    ],
    cta: "Apply Now",
  },
  {
    id: "travel-card",
    badge: "Travel",
    badgeTone: "travel",
    title: "Prepaid Card",
    network: "VISA",
    cardName: "Travel Card",
    benefits: [
      "Multi-currency support",
      "Zero forex charges",
      "Travel insurance",
      "Global ATM access",
    ],
    cta: "Apply Now",
  },
  {
    id: "student-card",
    badge: "Students",
    badgeTone: "students",
    title: "Debit Card",
    network: "RUPAY",
    cardName: "Student Card",
    benefits: [
      "Zero minimum balance",
      "Education discounts",
      "OTT subscriptions",
      "Study abroad support",
    ],
    cta: "Apply Now",
  },
];
