import { InvestmentProduct } from "@/types";
import { TrendingUp, Landmark, LineChart, Coins, ShieldCheck, Building } from "lucide-react";

export const INVESTMENT_PRODUCTS: InvestmentProduct[] = [
  {
    id: "mutual-funds",
    name: "Mutual Funds",
    tagline: "SIP from ₹500/month",
    description:
      "Invest in 5,000+ curated funds across equity, debt, and hybrid categories with SEBI-registered fund houses.",
    risk: "Medium Risk",
    badge: "Recommended",
    expectedReturn: "12–18% p.a.",
    minInvestment: "₹500",
    duration: "1–10 years",
    category: "Equity / Debt / Hybrid",
    suitableFor: "Long-term wealth creation",
    cta: "Invest Now",
    icon: TrendingUp,
  },
  {
    id: "fixed-deposits",
    name: "Fixed Deposits",
    tagline: "Guaranteed returns",
    description:
      "Earn guaranteed returns with flexible tenures. Senior citizen rates up to 7.7% p.a.",
    risk: "Low Risk",
    expectedReturn: "7.2% p.a.",
    minInvestment: "₹1,000",
    duration: "7 days – 10 years",
    category: "Fixed Income",
    suitableFor: "Conservative investors",
    cta: "Invest Now",
    icon: Landmark,
  },
  {
    id: "stocks",
    name: "Stocks",
    tagline: "Direct equity investing",
    description: "Trade 5,000+ NSE/BSE listed stocks with zero brokerage on delivery.",
    risk: "High Risk",
    expectedReturn: "Market-linked",
    minInvestment: "₹1",
    duration: "Any duration",
    category: "Equity",
    suitableFor: "Experienced investors",
    cta: "Invest Now",
    icon: LineChart,
  },
  {
    id: "digital-gold",
    name: "Digital Gold",
    tagline: "Start from ₹1",
    description: "99.9% pure digital gold backed by physical gold stored in insured vaults.",
    risk: "Low-Medium Risk",
    expectedReturn: "8–12% p.a.",
    minInvestment: "₹1",
    duration: "Flexible",
    category: "Commodity",
    suitableFor: "Inflation hedge seekers",
    cta: "Invest Now",
    icon: Coins,
  },
  {
    id: "retirement-plans",
    name: "Retirement Plans",
    tagline: "NPS & PPF",
    description: "Build a secure retirement corpus with tax-efficient NPS and PPF accounts.",
    risk: "Low Risk",
    expectedReturn: "9–11% p.a.",
    minInvestment: "₹500",
    duration: "Long-term",
    category: "Retirement",
    suitableFor: "Retirement planning",
    cta: "Invest Now",
    icon: ShieldCheck,
  },
  {
    id: "government-bonds",
    name: "Government Bonds",
    tagline: "Sovereign guarantee",
    description:
      "Invest in RBI-issued government securities with sovereign guarantee and regular interest payouts.",
    risk: "Very Low Risk",
    expectedReturn: "6.5–7.5% p.a.",
    minInvestment: "₹10,000",
    duration: "1–40 years",
    category: "Fixed Income",
    suitableFor: "Risk-averse investors",
    cta: "Invest Now",
    icon: Building,
  },
];
