import { LoanProduct } from "@/types";

export const LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: "personal-loan",
    name: "Personal Loan",
    rate: "10.5%",
    rateNote: "p.a. onwards",
    emiFrom: "₹2,187/mo",
    maxAmount: "₹25 Lakhs",
    tenure: "Up to 5 years",
    processingFee: "0.5%",
    approvalTime: "2 Hours",
    features: ["No collateral required", "Same-day disbursal", "Minimal documentation"],
    popular: true,
    cta: "Apply Now",
  },
  {
    id: "home-loan",
    name: "Home Loan",
    rate: "8.4%",
    rateNote: "p.a. onwards",
    emiFrom: "₹7,689/mo",
    maxAmount: "₹5 Crores",
    tenure: "Up to 30 years",
    processingFee: "0.25%",
    approvalTime: "48 Hours",
    features: ["Lowest EMI guarantee", "Balance transfer option", "Doorstep service"],
    cta: "Apply Now",
  },
  {
    id: "education-loan",
    name: "Education Loan",
    rate: "9.2%",
    rateNote: "p.a. onwards",
    emiFrom: "₹5,180/mo",
    maxAmount: "₹50 Lakhs",
    tenure: "Up to 15 years",
    processingFee: "Nil",
    approvalTime: "24 Hours",
    features: ["Study abroad coverage", "Moratorium period", "Tax benefit u/s 80E"],
    cta: "Apply Now",
  },
  {
    id: "business-loan",
    name: "Business Loan",
    rate: "12.0%",
    rateNote: "p.a. onwards",
    emiFrom: "₹11,224/mo",
    maxAmount: "₹2 Crores",
    tenure: "Up to 7 years",
    processingFee: "1%",
    approvalTime: "72 Hours",
    features: ["Working capital support", "Flexible repayment", "GST-linked eligibility"],
    cta: "Apply Now",
  },
  {
    id: "car-loan",
    name: "Car Loan",
    rate: "8.9%",
    rateNote: "p.a. onwards",
    emiFrom: "₹10,400/mo",
    maxAmount: "₹1 Crore",
    tenure: "Up to 7 years",
    processingFee: "0.5%",
    approvalTime: "4 Hours",
    features: ["100% on-road funding", "New & used cars", "Quick approval"],
    cta: "Apply Now",
  },
  {
    id: "loan-against-property",
    name: "Loan Against Property",
    rate: "9.5%",
    rateNote: "p.a. onwards",
    emiFrom: "₹10,450/mo",
    maxAmount: "₹10 Crores",
    tenure: "Up to 20 years",
    processingFee: "0.5%",
    approvalTime: "5 Days",
    features: ["Residential & commercial", "High loan amount", "Flexible end-use"],
    cta: "Apply Now",
  },
  // --- Added per request: Women Empowerment Loan ---
  {
    id: "women-empowerment-loan",
    name: "Women Empowerment Loan",
    rate: "7.5%",
    rateNote: "p.a. onwards",
    maxAmount: "₹25 Lakhs",
    tenure: "Flexible EMI",
    processingFee: "Nil",
    approvalTime: "Quick Approval",
    features: [
      "Women Entrepreneurs",
      "Startup Support",
      "Small Business",
      "Self Employment",
      "Easy Documentation",
      "Flexible EMI",
      "Quick Approval",
    ],
    cta: "Apply Now",
  },
];
